apiVersion: v1 
kind: Pod 
metadata:
  name: sa-frontend 
  labels:
    app: sa-frontend 
spec:
  containers:
    - image: patelsapna/rockstar-react-ui:minikube
      name: sa-frontend 
      ports:
        - containerPort: 80